### ISSUE TITLE
Firebase cant find package.json from paca

### ISSUE THREAD

**Issue by JoshRozin** [johnapost/nextjs-firebase-fns-demo#18]
Hey @johnapost , wasn't sure how to reach you directly but I'm wondering if you could help me with this issue I'm having. I've followed your medium article step by step, even deployed this project on my Firebase and all was well! However, I'm getting this issue on my own nextjs/firebase project. When I try to deploy my own project, I get this error.

`> cpx "src/app/static/**/*.*" dist/public/static

+  hosting: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing dist/functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: package.json does not exist at C:\package.json
    at Object.module.exports.FFJY.exports.find (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:13424:15)
    at Object.<anonymous> (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:34459:12)
    at Object.aazb (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:34493:30)
    at __webpack_require__ (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:23:31)
    at Object.svu+ (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:74155:12)
    at __webpack_require__ (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:23:31)
    at Object.e65k (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:57508:27)
    at __webpack_require__ (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:23:31)    at Object.<anonymous> (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:25234:14)
    at Object.P4Me (C:\Users\Josh\Desktop\pools-ssr-app\dist\functions\next\serverless\pages\index.js:25591:30)
Having trouble? Try firebase deploy --helperror Command failed with exit code 1.`

These errors all seem to lead to webpack having trouble finding the package.json file under the "client variable". If you have any ideas or questions, please let me know! Thanks for reading!

**Comment by JoshRozin** [comment]
Figured it out after two long days of trial and error! It was an issue with another plugin... specifically gRPC.
